<?php

use Detain\MyAdminPlesk\Plesk;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-26 at 08:02:17.
 */
class PleskTest extends TestCase
{
    /**
     * @var Plesk
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Plesk('host', 'login', 'password');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::randomString
     * @todo   Implement testRandomString().
     */
    public function testRandomString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::updateCurl
     * @todo   Implement testUpdateCurl().
     */
    public function testUpdateCurl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::curlInit
     * @todo   Implement testCurlInit().
     */
    public function testCurlInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::sendRequest
     * @todo   Implement testSendRequest().
     */
    public function testSendRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::parseResponse
     * @todo   Implement testParseResponse().
     */
    public function testParseResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::checkResponse
     * @todo   Implement testCheckResponse().
     */
    public function testCheckResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getErrorCodes
     * @todo   Implement testGetErrorCodes().
     */
    public function testGetErrorCodes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getError
     * @todo   Implement testGetError().
     */
    public function testGetError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createWebUser
     * @todo   Implement testCreateWebUser().
     */
    public function testCreateWebUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createCustomer
     * @todo   Implement testCreateCustomer().
     */
    public function testCreateCustomer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createMailAccount
     * @todo   Implement testCreateMailAccount().
     */
    public function testCreateMailAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getServerInfoTypes
     * @todo   Implement testGetServerInfoTypes().
     */
    public function testGetServerInfoTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::varExport
     * @todo   Implement testVarExport().
     */
    public function testVarExport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::fixResult
     * @todo   Implement testFixResult().
     */
    public function testFixResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getServerInfo
     * @todo   Implement testGetServerInfo().
     */
    public function testGetServerInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createSession
     * @todo   Implement testCreateSession().
     */
    public function testCreateSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getCustomers
     * @todo   Implement testGetCustomers().
     */
    public function testGetCustomers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getWebspaces
     * @todo   Implement testGetWebspaces().
     */
    public function testGetWebspaces()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getObjectStatusList
     * @todo   Implement testGetObjectStatusList().
     */
    public function testGetObjectStatusList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSiteFilters
     * @todo   Implement testGetSiteFilters().
     */
    public function testGetSiteFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSiteDatasets
     * @todo   Implement testGetSiteDatasets().
     */
    public function testGetSiteDatasets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSites
     * @todo   Implement testGetSites().
     */
    public function testGetSites()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSite
     * @todo   Implement testGetSite().
     */
    public function testGetSite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listSites
     * @todo   Implement testListSites().
     */
    public function testListSites()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSiteGenSetups
     * @todo   Implement testGetSiteGenSetups().
     */
    public function testGetSiteGenSetups()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createSite
     * @todo   Implement testCreateSite().
     */
    public function testCreateSite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::updateSite
     * @todo   Implement testUpdateSite().
     */
    public function testUpdateSite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::updateServer
     * @todo   Implement testUpdateServer().
     */
    public function testUpdateServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createSite2
     * @todo   Implement testCreateSite2().
     */
    public function testCreateSite2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createClient
     * @todo   Implement testCreateClient().
     */
    public function testCreateClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createDatabase
     * @todo   Implement testCreateDatabase().
     */
    public function testCreateDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createDatabaseUser
     * @todo   Implement testCreateDatabaseUser().
     */
    public function testCreateDatabaseUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createEmailAddress
     * @todo   Implement testCreateEmailAddress().
     */
    public function testCreateEmailAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createSecretKey
     * @todo   Implement testCreateSecretKey().
     */
    public function testCreateSecretKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createSiteAlias
     * @todo   Implement testCreateSiteAlias().
     */
    public function testCreateSiteAlias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createSubdomain
     * @todo   Implement testCreateSubdomain().
     */
    public function testCreateSubdomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getHtypes
     * @todo   Implement testGetHtypes().
     */
    public function testGetHtypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSubscriptionFilters
     * @todo   Implement testGetSubscriptionFilters().
     */
    public function testGetSubscriptionFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSubscriptionDatasets
     * @todo   Implement testGetSubscriptionDatasets().
     */
    public function testGetSubscriptionDatasets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::createSubscription
     * @todo   Implement testCreateSubscription().
     */
    public function testCreateSubscription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteSubscription
     * @todo   Implement testDeleteSubscription().
     */
    public function testDeleteSubscription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listSubscriptions
     * @todo   Implement testListSubscriptions().
     */
    public function testListSubscriptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteClient
     * @todo   Implement testDeleteClient().
     */
    public function testDeleteClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteDatabase
     * @todo   Implement testDeleteDatabase().
     */
    public function testDeleteDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteEmailAddress
     * @todo   Implement testDeleteEmailAddress().
     */
    public function testDeleteEmailAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteSecretKey
     * @todo   Implement testDeleteSecretKey().
     */
    public function testDeleteSecretKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteSiteAlias
     * @todo   Implement testDeleteSiteAlias().
     */
    public function testDeleteSiteAlias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteSite
     * @todo   Implement testDeleteSite().
     */
    public function testDeleteSite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::deleteSubdomain
     * @todo   Implement testDeleteSubdomain().
     */
    public function testDeleteSubdomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getClient
     * @todo   Implement testGetClient().
     */
    public function testGetClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getDatabaseUser
     * @todo   Implement testGetDatabaseUser().
     */
    public function testGetDatabaseUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getServicePlan
     * @todo   Implement testGetServicePlan().
     */
    public function testGetServicePlan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSubdomain
     * @todo   Implement testGetSubdomain().
     */
    public function testGetSubdomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getSubscription
     * @todo   Implement testGetSubscription().
     */
    public function testGetSubscription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::getTraffic
     * @todo   Implement testGetTraffic().
     */
    public function testGetTraffic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listClients
     * @todo   Implement testListClients().
     */
    public function testListClients()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listUsers
     * @todo   Implement testListUsers().
     */
    public function testListUsers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listDatabaseServers
     * @todo   Implement testListDatabaseServers().
     */
    public function testListDatabaseServers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listDatabases
     * @todo   Implement testListDatabases().
     */
    public function testListDatabases()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listDnsRecords
     * @todo   Implement testListDnsRecords().
     */
    public function testListDnsRecords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listEmailAddresses
     * @todo   Implement testListEmailAddresses().
     */
    public function testListEmailAddresses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listIpAddresses
     * @todo   Implement testListIpAddresses().
     */
    public function testListIpAddresses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listSecretKeys
     * @todo   Implement testListSecretKeys().
     */
    public function testListSecretKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listServicePlans
     * @todo   Implement testListServicePlans().
     */
    public function testListServicePlans()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listSiteAliases
     * @todo   Implement testListSiteAliases().
     */
    public function testListSiteAliases()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::listSubdomains
     * @todo   Implement testListSubdomains().
     */
    public function testListSubdomains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::renameSubdomain
     * @todo   Implement testRenameSubdomain().
     */
    public function testRenameSubdomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::updateClient
     * @todo   Implement testUpdateClient().
     */
    public function testUpdateClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::updateEmailPassword
     * @todo   Implement testUpdateEmailPassword().
     */
    public function testUpdateEmailPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminPlesk\Plesk::updateSubdomain
     * @todo   Implement testUpdateSubdomain().
     */
    public function testUpdateSubdomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
